from pydantic import BaseModel, Field
from typing import List

class ExecutionPlan(BaseModel):
    plan: list[str] = Field(
        description="A list of steps that the agent will take to execute the user's request. Allowed values: ['sql_agent', 'executor_tool', 'analyst_agent', 'synthesizer_node']"
        )

class SQLAgentOutput(BaseModel):
    sql_query: str = Field(description="The SQL query generated by the SQL agent based on the user's request. Use variables starting with $ if required to execute the query with the executor tool.")

class SQLVariable(BaseModel):
    name: str
    default: str
    type: str
    description: str | None = None

class GeneratedQuery(BaseModel):
    sql_query: str = Field(description="The parameterized DuckDB SQL query using $variable_name syntax.")
    sql_params: List[SQLVariable] = Field(description="A dictionary of the variables and their exact values needed to execute this specific query. You need to set the name, type, default value and description for each variable.")
